[profile.default]
src = "src"
lib = ["lib"]
test = "test"
script = "script"
solc_version = "0.8.30"
verbosity = 1

optimizer = true
optimizer_runs = 9_999_999

# File system permissions for FFI
fs_permissions = [
  { access = "read", path = "protocols" }
]

remappings = [
  "@mento/=lib/mento-core/contracts/",
  "@uniswap/v3-core/=lib/panoptic-v1-core/lib/v3-core/contracts/",
  "@uniswap/v3-periphery/=lib/panoptic-v1-core/lib/v3-periphery/contracts/",
  "@openzeppelin/=lib/openzeppelin-contracts/",

  "@uniswap/v4-core/=lib/bunni-v2/lib/v4-core/",
  "@uniswap/v4-utils/=lib/foundational-hooks/",

  "@panoptic/=lib/panoptic-v1-core/contracts/",
  "@panoptic/libraries/=lib/panoptic-v1-core/contracts/libraries/",
  "@panoptic/tokens/=lib/panoptic-v1-core/contracts/tokens/",
  "@panoptic/types/=lib/panoptic-v1-core/contracts/types/",
  "@panoptic/base/=lib/panoptic-v1-core/contracts/base/",

  "@compose/=lib/Compose/src/",

  "@bunni/=lib/bunni-v2/src/",

  "@liquidity-lab/=lib/Liquidity-Distributions-Lab/src/",

  "forge-std/=lib/panoptic-v1-core/lib/forge-std/src/",
  "@openzeppelin/=lib/panoptic-v1-core/lib/openzeppelin-contracts/",
  "solmate/=lib/panoptic-v1-core/lib/solmate/src/",
  "solady/=lib/solady/src/",
]

[rpc_endpoints]

mainnet = "${RPC_URL_MAINNET}"
arbitrum = "${RPC_URL_ARBITRUM}"
optimism = "${RPC_URL_OPTIMISM}"
base = "${RPC_URL_BASE}"
polygon = "${RPC_URL_POLYGON}"
sepolia = "${RPC_URL_SEPOLIA}"
