name: shelf
version: 0.1.0
language: GHC2021
default-extensions: [OverloadedStrings, StrictData, DerivingStrategies, LambdaCase]
ghc-options: [-Wall, -Wcompat, -Wincomplete-uni-patterns, -Wincomplete-record-updates, -Werror]
dependencies:
  - base >= 4.20 && < 5
  - aeson
  - binary
  - bytestring
  - case-insensitive
  - containers
  - crypton
  - directory
  - filepath
  - memory
  - text
  - time
  - typed-process
  - unix
  - yaml
library:
  source-dirs: src
  dependencies: [http-client, http-client-tls, http-types]
executables:
  shelf:
    main: Main.hs
    source-dirs: app
    dependencies: [shelf, optparse-applicative]
tests:
  shelf-test:
    main: Main.hs
    source-dirs: test
    dependencies:
      - shelf
      - case-insensitive
      - hedgehog
      - http-types
      - tasty
      - tasty-hedgehog
      - tasty-hunit
      - tasty-golden
      - temporary
      - wai
      - warp
